<template>
    <v-dialog :value="show" @input="$emit('cartClose')" width="1000">
        <v-card>
            <v-card-title>
                <v-container>
                    <v-layout headline>
                        Cart
                    </v-layout>
                </v-container>
                <v-spacer></v-spacer>
            </v-card-title>
            <v-card-text>
                <v-data-table
                    :headers="headers"
                    :items="$store.getters.cart.items"
                    class="elevation-1"
                    hide-actions
                >
                    <template v-slot:items="props">
                        <td class="text-xs-center">{{ props.item.name }}</td>
                        <td class="text-xs-center">
                            {{ props.item.variation.item_variation_data.name }}
                        </td>
                        <td class="text-xs-center">{{ props.item.quantity }}</td>
                        <td class="text-xs-center">
                            {{
                                centsToDollarString(
                                    props.item.variation.item_variation_data.price_money.amount
                                )
                            }}
                        </td>
                        <td class="text-xs-center">
                            {{
                                centsToDollarString(
                                    props.item.quantity *
                                        props.item.variation.item_variation_data.price_money.amount
                                )
                            }}
                        </td>
                        <td class="text-xs-center">
                            <v-btn @click="removeItem(props.item)" fab flat
                                ><v-icon>delete</v-icon></v-btn
                            >
                        </td>
                    </template>
                </v-data-table>
            </v-card-text>
            <v-card-actions>
                <v-container>
                    <v-layout justify-center align-center>
                        <v-btn
                            color="primary"
                            class="white--text"
                            large
                            hidden
                            v-if="cartHasItems"
                            :disabled="!checkoutReady"
                            :href="checkoutUrl"
                            target="_blank"
                        >
                            Checkout
                        </v-btn>
                    </v-layout>
                </v-container>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<script>
import axios from 'axios';

export default {
    name: 'CartDialog',
    props: ['show'],
    data() {
        return {
            checkoutReady: false, // variable determining if the checkout url is ready
            checkoutUrl: '', // variable holding the checkout url generated by backend
            headers: [
                {
                    text: 'Item',
                    value: 'item',
                    align: 'center',
                    sortable: false
                },
                {
                    text: 'Unit',
                    value: 'unit',
                    align: 'center',
                    sortable: false
                },
                {
                    text: 'Quantity',
                    value: 'quantity',
                    align: 'center',
                    sortable: false
                },
                {
                    text: 'Price per Unit',
                    value: 'pricepu',
                    align: 'center',
                    sortable: false
                },
                {
                    text: 'Price Total',
                    value: 'priceto',
                    align: 'center',
                    sortable: false
                },
                {
                    text: 'Remove',
                    value: 'remove',
                    align: 'center',
                    sortable: false
                }
            ]
        };
    },
    methods: {
        centsToDollarString(cents) {
            return '$' + cents / 100 + '.00';
        },
        removeItem(itemToRemove) {
            this.$store.commit('removeItemFromCart', itemToRemove);
            if (this.cartHasItems) {
                this.updateCheckoutUrl();
            }
        },
        updateCheckoutUrl() {
            this.checkoutReady = false;
            const GENERATE_CHECKOUT_URL =
                process.env.VUE_APP_API_BASE_URL + '/generate_checkout_url';
            axios
                .post(GENERATE_CHECKOUT_URL, this.$store.getters.cart) // ask for checkout url
                .then(response => {
                    this.checkoutReady = true;
                    this.checkoutUrl = response.data.url;
                    console.log(this.checkoutUrl);
                })
                .catch(error => {
                    console.log(error.response.status);
                    console.log(error.response.data);
                    this.checkoutReady = false;
                });
        }
    },
    computed: {
        cartHasItems() {
            return this.$store.getters.cart.items.length;
        }
    },
    watch: {
        show: function(newVal, oldVal) {
            if (newVal === true && this.cartHasItems) {
                // if showing dialog and items in cart
                this.updateCheckoutUrl();
            }
        }
    }
};
</script>
